#!/bin/bash
clear
echo -e "\33[32m The User & Their Details In The System: \33[0m"
echo -e "\33[42m _______________________________________\33[0m"
echo "  UserName  Userid  Groupid  Shell  HomeDirectory  secondaryGroup" 
echo "----  --------  ------  -------  -----  ---------------"
awk -F: '{print $1,$3,$4,$5}' /etc/passwd |more


